<a href="https://colab.research.google.com/github/gabrielalastra/test/blob/main/mean_std_var.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
x=[0,1,2,3,4,5,6,7,8]

In [3]:
x = np.array(x).reshape(3, 3)

In [4]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
mean_c = np.mean(x, axis=0)
mean_r = np.mean(x, axis=1)
mean_e = np.mean(x)

In [12]:
print(mean_c, mean_r, mean_e)


[3. 4. 5.] [1. 4. 7.] 4.0


In [13]:
#variance and standard desviation
var_c = np.var(x, axis=0)
var_r = np.var(x, axis=1)
var_e = np.var(x)
std_c = np.std(x, axis=0)
std_r = np.std(x, axis=1)
std_e = np.std(x)

In [14]:
#max&min
max_c = np.max(x, axis=0)
max_r = np.max(x, axis=1)
max_e = np.max(x)
min_c = np.min(x, axis=0)
min_r = np.min(x, axis=1)
min_e = np.min(x)

In [15]:
def calculate(x):
    dict = {
        'mean': [mean_r, mean_c, mean_e],
        'var': [var_r, var_c, var_e],
        'std': [std_r, std_c, std_e],
        'max': [max_r, max_c, max_e],
        'min': [min_r, min_c, min_e]
    }
    return dict


calculate(x)

{'max': [array([2, 5, 8]), array([6, 7, 8]), 8],
 'mean': [array([1., 4., 7.]), array([3., 4., 5.]), 4.0],
 'min': [array([0, 3, 6]), array([0, 1, 2]), 0],
 'std': [array([0.81649658, 0.81649658, 0.81649658]),
  array([2.44948974, 2.44948974, 2.44948974]),
  2.581988897471611],
 'var': [array([0.66666667, 0.66666667, 0.66666667]),
  array([6., 6., 6.]),
  6.666666666666667]}